server:
  port: 8888


spring:
  application:
    name: dubbo-provider
  cache:
    type: redis

  # 数据库相关的连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testbasedata?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      password: root
      username: root
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DateHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # redis的配置区
  redis:
    host: 127.0.0.1
    database: 1
    timeout: 20000
    port: 6379

  # 热部署
  devtools:
    restart:
      enabled: true
      #classpath目录下文件夹内容修改不重启
      #exclude:
      # 重启目录
      #additional-paths:


# 这是dubbo的配置
dubbo:
  application:
    name: dubbo-provider
    version: 1.0.0
  # dubbo 代理的名称与端口号
  protocol:
    name: dubbo
    port: 20880

  # 注册中心的注册地址
  registry:
    address: zookeeper://127.0.0.1:2181


  # 统一最好在服务提供者处编写，因为服务消费在调用的时候会将初始化这些配置使之起作用
  provider:
    timeout: 2000

#  scan:
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

# 日志
#logging:
#  level:
#    com:
#      moduls:
#        dubboprovider:
#          mapper: DEBUG
#  file: springboot.log


#    base-packages: com.moduls.dubboapi.service.UserService