server:
  port: 9999

spring:
  application:
    name: dubbo-consumer

dubbo:
  application:
    name: dubbo-consumer
    version: 1.0.0
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
